//ALL CARS
SELECT * FROM CAR;

//ALL CARS AVERAGE
SELECT AVG(C.VOTE)
FROM CAR C;

//AVERAGE PER MANUFACTURER OR MAKE
SELECT MAKE, AVG(C.VOTE)
FROM CAR C
GROUP BY C.MAKE;

//AVERAGE PER MAKE AND MODEL
SELECT C.MAKE, C.MODEL, AVG(C.VOTE)
FROM CAR C
GROUP BY C.MAKE, C.MODEL;

//ALL CELEBRITIES
SELECT * FROM CELEBRITY;

//AVERAGE FOR ALL CELEBRITIES WITH SAME NAME
SELECT C.NAME, AVG(C.VOTE)
FROM CELEBRITY C
GROUP BY C.NAME;

//AVERAGE FOR ALL CELEBRITIES WITH SAME NAME
SELECT C.NAME, C.SURNAME, AVG(C.VOTE)
FROM CELEBRITY C
GROUP BY C.NAME, C.SURNAME;